# Generated by Django 5.1.6 on 2025-02-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='views',
            new_name='subscribers',
        ),
    ]
